# build environment
FROM node:16-alpine as builder
WORKDIR /app
COPY ./package.json ./
RUN sed -i 's/localhost/api/g' package.json
RUN yarn install
COPY . .
RUN sed -i 's/localhost/api/g' package.json
RUN yarn run build

FROM nginx
EXPOSE 3000
COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]