FROM node:16-alpine
# i used this version where i can do command like sed, i tryed with node:16-alpine but doesnt work

WORKDIR /app

COPY package.json .

# RUN sed -i 's/localhost/api/g' package.json

RUN npm install

COPY . .

RUN sed -i 's/localhost/api/g' package.json

EXPOSE 3000



CMD ["npm", "start"]