version: '3.7'

services:
  api:
    # build:
    #   context: ./api
    #   dockerfile: Dockerfile.dev
    image: mveyone/workouts_api:latest
    container_name: api
    # command: /app/node_modules/.bin/nodemon server.js
    # volumes:
    #   - ./api/:/app
    #   - /app/node_modules
    ports:
      - "4000:4000"
    # depends_on:
    #   - mongo
    env_file: ./api/.env
    # environment:
    #   - NODE_ENV=development
    networks:
      - app-network
  # mongo:
  #   image: mongo
  #   volumes:
  #     - data-volume:/data/db
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - app-network
  client:
    # build:
      # context: ./client
      # dockerfile: Dockerfile.dev
    image: mveyone/workouts_api:latest
    container_name: client
    # command: npm start
    # volumes:
    #   - ./client/:/app
    #   - /app/node_modules
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    # node_modules:
    # web-root:
      driver: local