apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    email: mveyone@hotmail.com
    externalAccountBinding:
      keyID: W9cL_qTE6a2xy2emRtCDxw   ##EAB FROM ZERO SSL 
      keySecretRef:
        name: zero-ssl-eabsecret-2  ## name of secret
        key: secret
      keyAlgorithm: HS256     ## deprecated
    privateKeySecretRef:
      name: zerossl-prod
    solvers:
    - http01:
        ingress:
          class: nginx