apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mveyone@outlook.fr
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z065843931BKGKTPL826J
          region: us-east-1
      selector:
        dnsZones:
        - "am-devops.com"
    - http01:
        ingress:
          class: nginx